@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - List public figures in Figure catalogue
autonumber

actor "Show Designer" as SD
participant ":System" as System

activate SD

    SD -> System: login()
    activate System

    System --> SD: authenticated

    deactivate System
    SD -> System: ask to show all public figures

    activate System

    System --> SD: request data (id, keyname)
    deactivate System
    SD -> System: types requested data (id, keyname)

    activate System

    System --> SD: show all data registered for confirmation
    deactivate System

    SD -> System: requestDecommissionFigure(Figure)

    activate System


        System -> System: validations(...)
                activate System

                deactivate System

                alt figure inactive
                    System --> SD: errorMessage("Figure is already inactive.")
                else figure active
                    System -> System: decommissionFigure(Figure)
                    activate System

                    deactivate System

                    System --> SD: confirmationMessage("Figure *id* has been decommissioned.")
            deactivate System
                end
deactivate SD

@enduml
