@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - List Figure Categories

autonumber

actor "Show Designer" as SD
participant ":System" as System

activate SD

SD -> System: request all categories
activate System

System -> System: fetches all categories

System -> System: sorts categories by name

System --> SD: displays all categories

deactivate System
deactivate SD

@enduml
