@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "ShowDesigner" as ACTOR
participant ":ChangeCategoryStatusUI" as UI
participant ":ChangeCategoryStatusController" as CTRL
participant ":PersistenceContext" as PC
participant "factory\n:RepositoryFactory" as FACTORY_INSTANCE
participant "repository\n:FigureCategoryRepository" as REPO
participant "FigureCategory" as FigureCategory

activate ACTOR

ACTOR -> UI : requests change of category status

activate UI
UI -> CTRL : create()

activate CTRL
CTRL -> PC: repositories()
activate PC
PC -> FACTORY_INSTANCE: create()
activate FACTORY_INSTANCE
FACTORY_INSTANCE -> REPO: create()
deactivate FACTORY_INSTANCE
PC -> CTRL: FigureCategoryRepository
deactivate PC

UI -> UI: doShow()

UI -> CTRL: changeCategoryStatus(id, action)
CTRL -> CTRL: validate(id, action)
alt invalid input or already in requested status
    CTRL -> UI: errorMessage("Invalid request or category already in requested status")
else valid input
    CTRL -> REPO: findById(id)
    REPO -> CTRL: FigureCategory
    CTRL -> FigureCategory: updateStatus(action)
    CTRL -> REPO: save(FigureCategory)
    REPO -> CTRL: confirmation
    CTRL -> UI: successMessage("Category status updated successfully")
end

deactivate CTRL
deactivate UI
deactivate ACTOR

@enduml
