@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title UI Sequence Diagram (SSD) - Inactivate/Activate Figure Category

autonumber

actor "Show Designer" as showDesigner
participant ":ChangeCategoryStatusUI" as UI
participant ":ChangeCategoryStatusController" as CTRL
participant "figureCategoryController\n:FigureCategoryController" as catCtrl
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "figureCategoryRepository\n:FigureCategoryRepository" as catRepo

activate showDesigner

    showDesigner -> UI : ask to change category status
    activate UI

    UI -> catRepo : getChangeableCategories()
    activate catRepo
        catRepo --> UI : listOfCategories
    deactivate catRepo

    UI -> showDesigner : show categories and ask for selection
    showDesigner -> UI : selects category (categoryId) and action (activate/inactivate)

    UI -> catRepo : getCategoryById(categoryId)
    activate catRepo
        catRepo --> UI : categoryObject
    deactivate catRepo

    UI -> CTRL : create
    activate CTRL

        CTRL -> CTRL : getFigureCategoryRepository()
        activate CTRL

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getFigureCategoryRepository()
            activate PLAT

                PLAT --> CTRL: figureCategoryRepository
            deactivate PLAT
            CTRL --> CTRL : figureCategoryRepository

        deactivate CTRL

        CTRL -> catRepo : findById(categoryId)
        activate catRepo
            catRepo --> CTRL : figureCategoryObject
        deactivate catRepo

        CTRL -> catCtrl : validateChangeCategoryStatus(figureCategoryObject, action)
        activate catCtrl
            catCtrl --> catCtrl : validations()
            alt invalid input or already in requested status
                catCtrl --> CTRL : error("Invalid request or category already in requested status")
                CTRL -> UI : error("Invalid request or category already in requested status")
                deactivate CTRL
                deactivate UI
                deactivate showDesigner
                return
            else valid input
                catCtrl --> CTRL : validationSuccess
            end
        deactivate catCtrl

        CTRL -> figureCategory : updateStatus(action)
        activate figureCategory
            figureCategory --> CTRL : updatedCategoryObject
        deactivate figureCategory

        CTRL -> catRepo : save(updatedCategoryObject)
        activate catRepo
            catRepo --> CTRL : confirmation
        deactivate catRepo

        CTRL -> UI : updatedCategoryObject
    deactivate CTRL

    UI -> showDesigner : shows operation (in)success

deactivate UI
deactivate showDesigner

@enduml
