@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title UI Sequence Diagram (SSD) - Add Figure Category

autonumber

actor "Show Designer" as showDesigner
participant ":AddFigureCategoryUI" as UI
participant ":AddFigureCategoryController" as CTRL
participant "figureCategoryController\n:FigureCategoryController" as catCtrl
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "figureCategoryRepository\n:FigureCategoryRepository" as catRepo

participant "factoryProvider\n:FactoryProvider" as factProv
participant "figureCategoryFactoryImpl\n:FigureCategoryFactoryImpl" as catFactImpl
participant "figureCategory\n:FigureCategory" as figureCategory
participant "figureCategoryJPAImpl\n:FigureCategoryJPAImpl" as catJPA
participant "inMemoryFigureCategoryRepository\n:InMemoryFigureCategoryRepository" as catMem

participant "localDateTime\n:LocalDateTime" as localTime

activate showDesigner

    showDesigner -> UI : ask to add a Figure Category
    activate UI

    UI -> showDesigner : ask for category data (name, description)
    showDesigner -> UI : provides category data

    UI -> CTRL** : create

    activate CTRL

        CTRL -> CTRL : getFigureCategoryRepository()
        activate CTRL

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getFigureCategoryRepository()
            activate PLAT

                PLAT --> CTRL: figureCategoryRepository
            deactivate PLAT
            CTRL --> CTRL : figureCategoryRepository

        deactivate CTRL

        CTRL -> factProv : getFigureCategoryFactory()
        activate factProv

            factProv --> CTRL : categoryFactory
        deactivate factProv

        CTRL -> catFactImpl : createFigureCategory(name, description)
        activate catFactImpl
            catFactImpl --> catFactImpl : validations()
            alt invalid input
                catFactImpl --> CTRL : error("Invalid or duplicate category name/description")
                CTRL -> UI : error("Invalid or duplicate category name/description")
                deactivate CTRL
                deactivate UI
                deactivate showDesigner
                return
            else valid input
                catFactImpl -> figureCategory**: create

                catFactImpl --> CTRL : figureCategoryObject
                activate CTRL

            end
        deactivate catFactImpl

        CTRL -> localTime** : getCurrentMoment()
        activate localTime

            localTime --> CTRL : createdOn
        deactivate localTime

        CTRL -> catJPA : add(figureCategoryObject)
        deactivate catFactImpl
        activate catJPA

            catJPA --> CTRL : confirmation
        deactivate catJPA

        CTRL -> catMem : add(figureCategoryObject)
        activate catMem

            catMem --> CTRL : confirmation
        deactivate catMem

        CTRL -> UI : figureCategoryObject
    deactivate CTRL

    UI -> showDesigner : shows operation (in)success

deactivate UI
deactivate showDesigner

@enduml
