package proposal_template.validators;

// Imports the base visitor and parser classes generated by ANTLR
import proposal_template.generated.templateBaseVisitor;
import proposal_template.generated.templateParser;

import java.util.*;

/**
 * TemplateFieldVisitor is an ANTLR parse tree visitor that collects all placeholder field names
 * found in a parsed template.
 *
 * It extends the generated `templateBaseVisitor` class, overriding only the visitField method.
 */
public class TemplateFieldVisitor extends templateBaseVisitor<Void> {

    // Stores the set of all unique field names encountered (e.g., "CUSTOMER_NAME")
    private final Set<String> allFields = new HashSet<>();

    /**
     * Visits a FIELD node in the parse tree, extracts the field name (without the ${ and }),
     * and stores it in the set of field names.
     */
    @Override
    public Void visitField(templateParser.FieldContext ctx) {
        String field = ctx.FIELD().getText();
        String fieldName = field.substring(2, field.length() - 1);
        allFields.add(fieldName);

        return super.visitField(ctx);
    }

    /**
     * Returns the set of all field names found in the template.
     */
    public Set<String> getFields() {
        return allFields;
    }
}
