@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title UI Sequence Diagram (SSD) - Authentication Flow

autonumber

actor "System User" as user
participant ":LoginUI" as UI
participant ":AuthenticationController" as CTRL
participant ":RepositoryProvider" as repoProvider
participant ":AuthenticationRepository" as authRepoInterface
participant ":AuthenticationRepositoryJPAImpl" as authJPA
participant ":InMemoryAuthenticationRepository" as authMEM
participant ":AuthFacade" as facade
participant ":UserStore" as userStore
participant ":UserRoleStore" as roleStore
participant ":UserSession" as session

== START ==

user -> UI : inputs email + password
UI -> CTRL : doLogin(email, password)
activate CTRL

CTRL -> repoProvider : authenticationRepository()
activate repoProvider
repoProvider --> CTRL : authRepoInterface
deactivate repoProvider

CTRL -> authRepoInterface : doLogin(email, password)
activate authRepoInterface

alt Using InMemoryAuthenticationRepository
    activate authMEM
    authRepoInterface -> authMEM
    authMEM -> facade : doLogin(email, password)
    facade -> userStore : getById(email)
    userStore --> facade : user
    facade -> facade : verifyPassword()
    alt valid
        facade -> session : new UserSession(user)
        session --> facade : success
        facade --> authMEM : session
        authMEM --> CTRL : true
    else invalid
        facade --> authMEM : session (null)
        authMEM --> CTRL : false
    end
    deactivate authMEM

else Using AuthenticationRepositoryJPAImpl
    activate authJPA
    authRepoInterface -> authJPA
    authJPA -> authJPA : findById(email)
    authJPA --> authJPA : user
    authJPA -> authJPA : verifyPassword()
    alt valid
        authJPA --> authJPA : setLoggedUser(user)
        authJPA --> CTRL : true
    else invalid
        authJPA --> CTRL : false
    end
    deactivate authRepoInterface
    deactivate authJPA

end

CTRL --> UI : returns success/failure


@enduml
