@startuml
skinparam classAttributeIconSize 0

title Class Diagram - US213 - List Users

package "usermanagement.domain" {
    class User {
        - Email id
        - Password password
        - String name
        - String phoneNumber
        - boolean active
        - UserRole role
        + isActive(): boolean
        + getId(): Email
        + getName(): String
    }

    class Email {
        - String value
    }

    class Password {
        - String hashedValue
    }

    User --> Email
    User --> Password
}

package "usermanagement.application" {
    class ListUserController {
        + getAllUsers(): List<User>
        + getAllUsersWithStatus(): List<String>
    }

    interface UserRepository {
        + findAll(): List<User>
    }
}

ListUserController --> UserRepository
ListUserController --> User : reads >
@enduml
