@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Inactivate/Activate Figure Category

autonumber

actor "Show Designer" as SD
participant ":System" as System

activate SD

SD -> System: requests to change the current category availability
activate System
System -> System: fetches all categories
System --> SD: sends all categories for user to choose

SD -> System: chooses the category
System -> System: changes the chosen category status

System --> SD: informs user about the successful operation


deactivate System
deactivate SD

@enduml
