@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
left to right direction

title Drone and DroneModel Domain Model Section

hide circles
hide methods

package "Drone Aggregate" {

    class Drone <<AggregateRoot>> {

    }

    class SerialNumber <<ValueObject>> {
    }

    class DroneStatus <<ValueObject>> {
    }

    class DroneRemovalLog <<ValueObject>> {
    }
}

package "DroneModel Aggregate" {

    class DroneModel <<AggregateRoot>> {
    - maxWindSpeed <<int>>
    }

    class DroneModelID <<ValueObject>> {
    }

    class DroneName <<ValueObject>> {
    }

    class Description <<ValueObject>> {
    }

    class WindTolerance <<ValueObject>> {
    }
}

Drone "*" --- "1" DroneModel : >
Drone "1" --- "1" SerialNumber : >
Drone "1" --- "1" DroneStatus : >
Drone "1" --- "*" DroneRemovalLog : >
DroneModel "1" --- "1" DroneModelID : >
DroneModel "1" --- "1" DroneName : >
DroneModel "1" --- "1" Description : >
DroneModel "1" --- "*" WindTolerance : >

@enduml