@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title UI Sequence Diagram (SSD) - Disable/Enable User Flow (US212)

autonumber

actor "Admin User" as user
participant "ManageUserUI" as UI
participant "FilterUsersController" as filterCtrl
participant "CheckUserStatusController" as checkCtrl
participant "UserStatusController" as statusCtrl
participant "User" as userEntity
participant "UserRepository" as userRepo
participant "AuthenticationRepository" as authRepo

== START ==

user -> UI : run()

activate UI
    UI -> filterCtrl : getUsersByFilter(filterIndex)
    activate filterCtrl
        filterCtrl -> userRepo : getAllUsers()
    activate userRepo
        userRepo --> filterCtrl : List<User>
    deactivate userRepo
    deactivate filterCtrl

    UI -> UI : show list and get selection

    UI -> checkCtrl : isUserActive(user)
    activate checkCtrl
    checkCtrl --> UI : boolean
    deactivate checkCtrl

    UI -> statusCtrl : changeUserStatus(user, !user.isActive())
    activate statusCtrl
        alt activating
            statusCtrl -> userEntity : activate()
            activate userEntity
        else deactivating
            statusCtrl -> userEntity : deactivate()
        end
        deactivate userEntity
        statusCtrl -> userRepo : save(user)
        statusCtrl -> authRepo : setUserActive(userId, status)

    deactivate statusCtrl

    UI -> user : show success/fail message

deactivate UI
@enduml
