import org.antlr.v4.runtime.*;
import org.antlr.v4.runtime.tree.*;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Test class for validating the Figures DSL parser generated by ANTLR (Figures.g4).
 * Covers valid and invalid syntax cases to ensure the grammar correctly parses input.
 */
public class FiguresParserTest {

    /**
     * Utility method to parse input DSL code using the FiguresLexer and FiguresParser.
     * Throws RuntimeException if syntax errors are encountered.
     *
     * @param code DSL input string
     * @return ParseTree generated by parser
     * @throws Exception on lexer/parser failures
     */
    private ParseTree parse(String code) throws Exception {
        CharStream input = CharStreams.fromString(code);
        FiguresLexer lexer = new FiguresLexer(input);
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        FiguresParser parser = new FiguresParser(tokens);

        // Remove default error listeners and add custom one that throws exceptions on syntax errors
        parser.removeErrorListeners();
        parser.addErrorListener(new BaseErrorListener() {
            @Override
            public void syntaxError(Recognizer<?, ?> recognizer,
                                    Object offendingSymbol,
                                    int line, int charPositionInLine,
                                    String msg, RecognitionException e) {
                throw new RuntimeException("syntax error at line " + line + ":" + charPositionInLine + " - " + msg);
            }
        });

        return parser.program();
    }

    @Test
    void testValidDroneTypeDeclaration() throws Exception {
        String code = "DroneType MyDrone;";
        ParseTree tree = parse(code);
        assertNotNull(tree);
    }

    @Test
    void testValidVariablePositionDeclaration() throws Exception {
        String code = "Position startPos = (0,0,0);";
        ParseTree tree = parse(code);
        assertNotNull(tree);
    }

    @Test
    void testValidInstantiation() throws Exception {
        String code = "DroneType drone1();";
        ParseTree tree = parse(code);
        assertNotNull(tree);
    }

    @Test
    void testValidSegmentWithStatements() throws Exception {
        String code = "before\n" +
                "Position pos1 = (1,2,3);\n" +
                "pause(5);\n" +
                "endbefore";
        ParseTree tree = parse(code);
        assertNotNull(tree);
    }

    @Test
    void testInvalidMissingSemicolon() {
        String code = "Position startPos = (0,0,0)";
        Exception exception = assertThrows(RuntimeException.class, () -> parse(code));
        assertTrue(exception.getMessage().contains("syntax error"));
    }

    @Test
    void testFunctionCallWithArguments() throws Exception {
        String code = "drone1.move((1,2,3));";
        ParseTree tree = parse(code);
        assertNotNull(tree);
    }
}
