@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
left to right direction

title Complete Domain Model - US315 (ShowProposal)

hide circles
hide methods

package "Show Proposal Aggregate" {

    class ShowProposal <<AggregateRoot>> {
    }

    class ShowRequest
    class ProposalTemplate
    class Figure
    class DroneModel
    class Description
    class Location
    class Video
    class ShowProposalStatus
}

ShowProposal "1" --- "1" ShowRequest : refers >
ShowProposal "1" --- "1" ProposalTemplate : uses >
ShowProposal "1" --- "*" Figure : sequenceFigures >
ShowProposal "1" --- "*" DroneModel : modelsUsed >

ShowProposal "1" --- "1" Description : embedded >
ShowProposal "1" --- "1" Location : embedded >
ShowProposal "1" --- "1" Video : embedded >
ShowProposal "1" --- "1" ShowProposalStatus : status >

@enduml
