@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US212 - Disable/Enable User

autonumber

actor "Admin" as Admin
participant ":System" as System

activate Admin

    Admin -> System : toggleUserStatus(userId, desiredStatus)
    activate System

        System -> System : verifyAdminPermissions()
        System -> System : listUsers()
        System -> System : disable/enable()

        alt user exists
            System -> System : updateUserStatus(userId, desiredStatus)
            System -> System : persistUserStatusChange()
            System --> Admin : status update successful
        else error (user not found or trying to disable self)
            System --> Admin : status update failed
        end

    deactivate System

deactivate Admin
@enduml
