@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Edit Figure Category

autonumber

actor "Show Designer" as SD
participant ":System" as System

activate SD

SD -> System: requests to edit Figure Category
activate System
System -> System: fetches all categories
System --> SD: sends all categories for user to choose
SD -> System : chooses the category to edit and edits fields
System -> System: validates Category name
System -> System: checks Category's name uniqueness
System -> System: validates description

alt Duplicated name
 System --> SD: error message (duplicated name)
else Category exists

    alt Category is inactive
        System --> SD: errorMessage("Cannot edit inactive category")
    else Category is active
        System --> SD: informs user about the successful operation

    end
end

deactivate System
deactivate SD

@enduml
