@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title UI Sequence Diagram (SSD) - List Figure Categories

autonumber

actor "Show Designer" as showDesigner
participant ":ListFigureCategoriesUI" as UI
participant ":ListFigureCategoriesController" as CTRL
participant "figureCategoryController\n:FigureCategoryController" as catCtrl
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "figureCategoryRepository\n:FigureCategoryRepository" as catRepo

activate showDesigner

    showDesigner -> UI : ask to list Figure Categories
    activate UI

    UI -> CTRL : create
    activate CTRL

        CTRL -> CTRL : getFigureCategoryRepository()
        activate CTRL

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getFigureCategoryRepository()
            activate PLAT

                PLAT --> CTRL: figureCategoryRepository
            deactivate PLAT
            CTRL --> CTRL : figureCategoryRepository

        deactivate CTRL

        UI -> UI: doShow()

        UI -> CTRL: listFigureCategories()
        CTRL -> catRepo: findAllActiveOrderedByName()
        activate catRepo
            catRepo --> CTRL: listOfCategories
        deactivate catRepo
        CTRL -> UI: displayCategories(listOfCategories)

    deactivate CTRL

    UI -> showDesigner : shows list of categories

deactivate UI
deactivate showDesigner

@enduml
