package figure_dsl.validator;

import figure_dsl.generated.dslBaseVisitor;
import figure_dsl.generated.dslParser.Drone_modelContext;

/**
 * Validator class for checking the drone model declaration in the DSL.
 * Extends the base visitor generated by ANTLR to override the
 * visit method for drone model nodes.
 */
public class DroneModelValidator extends dslBaseVisitor<Void> {
    // Reference to the main validation plugin, used for tracking state and reporting errors
    private final FigureValidationPlugin validator;

    /**
     * Constructor initializing with the main validator instance.
     * @param validator the central validation plugin to use for error reporting and tracking
     */
    public DroneModelValidator(FigureValidationPlugin validator) {
        this.validator = validator;
    }

    /**
     * Visits a drone_model node in the parse tree.
     * Validates that only one drone model is declared.
     * If multiple declarations are found, reports an error.
     * If this is the first declaration, records the model name.
     *
     * @param ctx the context of the drone_model node containing the parsed information
     * @return null (required by visitor pattern)
     */
    @Override
    public Void visitDrone_model(Drone_modelContext ctx) {
        validator.incrementDroneModelCount();

        if (validator.getDroneModelCount() == 1) {
            String modelName = ctx.ID().getText();
            validator.setDroneModelName(modelName);
            validator.addDroneModel(modelName);
        } else {
            validator.addError("Error at line " + ctx.getStart().getLine() +
                    ": Multiple drone model declarations found. Only one 'DroneType' is allowed.");
        }
        return null;
    }
}
