package figure_dsl.validator;

import figure_dsl.generated.dslBaseVisitor;
import figure_dsl.generated.dslParser;

// Validator class for checking the DSL version declaration in the parsed DSL file.
// It extends the base visitor generated by ANTLR to traverse the parse tree.
public class DslVersionValidator extends dslBaseVisitor<Void> {
    // Reference to the validation plugin that manages errors and metadata
    private final FigureValidationPlugin plugin;

    // Constructor that receives the validation plugin instance for reporting errors and storing info
    public DslVersionValidator(FigureValidationPlugin plugin) {
        this.plugin = plugin;
    }

    // Override the visit method for the root 'dsl' rule in the grammar.
    // This method is called when visiting the top-level DSL context.
    @Override
    public Void visitDsl(dslParser.DslContext ctx) {

        if (ctx.version() == null) {
            plugin.addError("Missing DSL version declaration");
        } else {
            String version = ctx.version().VERSION_NUMBER().getText();
            if (!version.matches("\\d+(\\.\\d+)+")) {
                plugin.addError("Invalid version format. Use X.Y.Z");
            }
            plugin.setDslVersion(version);
        }
        return super.visitDsl(ctx);
    }
}

