@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title UI Sequence Diagram (SSD) - List public figures in Figure Catalogue

autonumber

actor "Show Designer" as showDesigner
participant ":ListFigureUI" as UI
participant ":ListFigureController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "figureRepository\n:FigureRepository" as catRepo

activate showDesigner

    showDesigner -> UI : ask to list public figures
    activate UI

    UI -> showDesigner : ask for pages data (page, pagesize)
    showDesigner -> UI : provides pages data

    UI -> CTRL** : create

    activate CTRL

        CTRL -> CTRL : getFigureRepository()
        activate CTRL

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getFigureRepository()
            activate PLAT

                PLAT --> CTRL: figureRepository
            deactivate PLAT
            CTRL --> CTRL : figureRepository

        deactivate CTRL

        UI -> CTRL: displayPublicFigures(page, pagesize)
                CTRL -> catRepo: findAllPublicFigures()
                activate catRepo

                    catRepo --> CTRL: listOfPublicFigures
                deactivate catRepo
                CTRL -> UI: listOfPublicFigures

            deactivate CTRL

            UI -> showDesigner : shows list of Public Figures

deactivate UI
deactivate showDesigner

@enduml
