@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
left to right direction

title Show Proposal Domain Model - US310

hide circles
hide methods

package "Show Proposal Aggregate" {

    class ShowProposal <<AggregateRoot>> {
    }

    class ShowProposalId <<ValueObject>> {
    }

    class ShowRequestId <<ValueObject>> {
    }

    class Template <<ValueObject>> {
    }

    class NumberOfDrones <<ValueObject>> {
    }

    class ShowDate <<ValueObject>> {
    }

    class Location <<ValueObject>> {
    }

    class Description <<ValueObject>> {
    }

    class ShowDuration <<ValueObject>> {
    }

    class Status <<ValueObject>> {
    }

    class CreatedAt <<ValueObject>> {
    }

    class CreatedBy <<ValueObject>> {
    }

    class Video <<ValueObject>> {
    }

}

package "Figure Aggregate" {

    class Figure <<AggregateRoot>> {
    }
}

ShowProposal "1" --- "1" ShowProposalId : >
ShowProposal "1" --- "1" ShowRequestId : >
ShowProposal "1" --- "1" Template : >
ShowProposal "1" --- "1" NumberOfDrones : >
ShowProposal "1" --- "1" ShowDate : >
ShowProposal "1" --- "1" Location : >
ShowProposal "1" --- "1" Description : >
ShowProposal "1" --- "1" ShowDuration : >
ShowProposal "1" --- "1" Status : >
ShowProposal "1" --- "1" CreatedAt : >
ShowProposal "1" --- "1" CreatedBy : >
ShowProposal "1" --- "0..1" Video : >

ShowProposal "1" ----- "*" Figure :  >

@enduml
