@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
'skinparam shadowing false

skinparam rectangle{
    BorderColor pink
}

title Use Case Diagram

left to right direction

rectangle "System Actors                       " as actors {
    actor "Actor" as AC


}



rectangle "Use Cases" as usecases{
    usecase "UC101 - Blabla" as UC101
    usecase "UC102 - Blabla" as UC102
    usecase "UC1033 - Blabla" as UC103
    usecase "UC104 - Blabla" as UC104
    usecase "UC105 - Blabla" as UC105
    usecase "UC110 - Blabla" as UC110
    AC --> UC101
    AC --> UC102
    AC --> UC103
    AC --> UC104
    AC --> UC105
    AC --> UC110

}


@enduml