@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title UI Sequence Diagram (SSD) - Search Figure catalogue

autonumber

actor "Show Designer" as showDesigner
participant ":ListSearchedFigureUI" as UI
participant ":ListSearchedFigureController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT

participant "figureCategoryController\n:FigureCategoryController" as figureCategoryControler
participant ":AddFigureController" as CTRL
participant "authenticationController\n:AuthenticationController" as authcot
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "figureCategoryRepository\n:FigureCategoryRepository" as figureCategoryRepository
participant "authenticationRepository\n:AuthenticationRepository" as authenticationRepository

activate showDesigner

    showDesigner -> UI : ask to search figures
    activate UI

    UI -> showDesigner : ask for optional data (id, name, description, version, availability dsl, status)
    showDesigner -> UI : provides optional data
    UI -> figureCategoryControler** : getActiveFigureCategories()


                    activate figureCategoryControler

                    figureCategoryControler --> figureCategoryControler : getFigureCategoryRepository()

                    activate figureCategoryControler

                        figureCategoryControler -> RepositorySingleton : getInstance()
                        activate RepositorySingleton

                            RepositorySingleton --> figureCategoryControler : repositories
                        deactivate RepositorySingleton

                        figureCategoryControler -> PLAT : getFigureCategoryRepository()

                        activate PLAT

                            PLAT --> figureCategoryControler : figureCategoryRepository
                        deactivate PLAT

                            figureCategoryControler --> figureCategoryControler: figureCategoryRepository
                    deactivate figureCategoryControler

                        figureCategoryControler -> figureCategoryRepository : getActiveFigureCategories(CostumerID identification)


                        activate figureCategoryRepository

                        figureCategoryRepository --> figureCategoryControler : listWithActiveFigureCategories

            deactivate figureCategoryRepository
            figureCategoryControler --> UI : listWithActiveFigureCategories
            deactivate figureCategoryControler
    UI -> showDesigner : ask for optional category selection
      deactivate UI

showDesigner -> UI : provides optional category
activate UI

UI -> authcot ** : getMyActiveCustomers()
deactivate CTRL
        activate authcot
            authcot --> authcot : getAuthenticationRepository()
            activate authcot

                authcot -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                RepositorySingleton --> authcot : repositories
                deactivate RepositorySingleton

                authcot -> PLAT : getAuthenticationRepository()
                activate PLAT

                    PLAT --> authcot  : authenticationRepository
                deactivate PLAT
                    authcot --> authcot : authenticationRepository
                    |||
            deactivate authcot

            authcot -> authenticationRepository  : getMyActiveCustomers()
            activate authenticationRepository

                authenticationRepository --> authcot : listActiveCustomers
            deactivate authenticationRepository

            authcot --> UI : listActiveCustomers

        deactivate authcot
    UI -> showDesigner : ask for optional costumer selection

  deactivate UI

  showDesigner -> UI : provides optional costumer
activate UI

    UI -> CTRL** : create
    activate CTRL

        CTRL -> CTRL : getFigureRepository()
        activate CTRL

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getFigureRepository()
            activate PLAT

                PLAT --> CTRL: figureRepository
            deactivate PLAT
            CTRL --> CTRL : figureRepository

        deactivate CTRL

        UI -> CTRL: searchFigure(id, name, description, version, availability, category, dsl, status, costumer)

alt Repository is InMemoryFigureRepository
    CTRL -> inMem: findFigures(id, name, description, version, availability, category, dsl, status, costumer)
    activate inMem

    inMem --> CTRL: Optional<List<Figure>>
    deactivate inMem

else Repository is FigureRepositoryJPAImpl
    CTRL -> jpa: findFigures(id, name, description, version, availability, category, dsl, status, costumer)
    activate jpa

    jpa --> CTRL: Optional<List<Figure>>
    deactivate jpa
end
                CTRL -> UI: listOfFigures

            deactivate CTRL

            UI -> showDesigner : shows list of searched Figures

deactivate UI
deactivate showDesigner

@enduml
