@startuml
skinparam classAttributeIconSize 0

title Class Diagram - US220 - Register Customer

package "customermanagement.domain" {
    class Costumer {
        - Name name
        - EmailAddress email
        - PhoneNumber phone
        - NIF nif
        - Address address
        + getNIF(): NIF
        + getName(): Name
    }

    class CustomerRepresentative {
        - Name name
        - Email email
        - PhoneNumber phone
        - String position
        + getEmail(): Email
    }

    class Name {
        - String value
    }

    class EmailAddress {
        - String value
    }

    class Email {
        - String email
    }

    class PhoneNumber {
        - String value
    }

    class NIF {
        - String value
    }

    class Address {
        - String fullAddress
    }

    Costumer --> Name
    Costumer --> EmailAddress
    Costumer --> PhoneNumber
    Costumer --> NIF
    Costumer --> Address

    CustomerRepresentative --> Name
    CustomerRepresentative --> Email
    CustomerRepresentative --> PhoneNumber
}

package "customermanagement.application" {
    class RegisterCustomerController {
        + registerCustomer(...): Optional<Costumer>
    }

    class RegisterRepresentativeController {
        + registerRepresentative(...): boolean
    }

    class RegisterUserController {
        + registerUser(...): boolean
    }

    interface CostumerRepository {
        + saveInStore(Costumer, NIF): Optional<Costumer>
    }

    interface CustomerRepresentativeRepository {
        + save(CustomerRepresentative): void
    }

    RegisterCustomerController --> CostumerRepository
    RegisterCustomerController --> Costumer : creates >

    RegisterRepresentativeController --> CustomerRepresentativeRepository
    RegisterRepresentativeController --> CustomerRepresentative : creates >
    RegisterRepresentativeController --> RegisterUserController : uses >
}

@enduml
