@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title UI Sequence Diagram (SSD) - Edit Figure Category

autonumber

actor "Show Designer" as SD
participant ":EditFigureCategoryUI" as UI
participant ":EditFigureCategoryController" as CTRL
participant ":GetAllFigureCategoriesController" as FetchCtrl
participant "RepositoryProvider" as Provider
participant "FigureCategoryRepository" as Repo
participant "InMemoryFigureCategoryRepository" as InMemRepo
participant "FigureCategoryJPAImpl" as JpaRepo
participant "FigureCategory" as Entity



activate SD
SD -> UI : request to edit a Figure Category
activate UI

UI -> FetchCtrl : getAllFigureCategories()
activate FetchCtrl

FetchCtrl -> Provider** : figureCategoryRepository()
activate Provider
Provider --> FetchCtrl : FigureCategoryRepository
deactivate Provider


activate Repo
FetchCtrl -> Repo : findAll()

alt using InMemoryFigureCategoryRepository
    Repo -> InMemRepo : findAll()
    activate InMemRepo

    InMemRepo --> Repo : List<FigureCategory>
    deactivate InMemRepo
else using FigureCategoryJPAImpl
    Repo -> JpaRepo : findAll()
    activate JpaRepo

    JpaRepo --> Repo : List<FigureCategory>
    deactivate JpaRepo
end


Repo -> FetchCtrl: Optional<List<FigureCategory>>
deactivate Repo


FetchCtrl --> UI : Optional<List<FigureCategory>>
deactivate FetchCtrl

UI -> SD : show categories to choose from

SD -> UI : selects category and fields to edit
UI -> CTRL : editChosenCategory(category, newName?, newDescription?)
activate CTRL

CTRL -> Provider : figureCategoryRepository()
activate Provider
Provider --> CTRL : FigureCategoryRepository
deactivate Provider

CTRL -> Repo : editChosenCategory(category, newName?, newDescription?)
activate Repo

alt InMemoryFigureCategoryRepository
    Repo -> InMemRepo : editChosenCategory()
    activate InMemRepo

    InMemRepo -> Entity : changeCategoryNameTo() / changeDescriptionTo()
    activate Entity

    Entity -> InMemRepo : FigureCategory
    deactivate Entity

    InMemRepo --> Repo : Optional<FigureCategory>
else FigureCategoryJPAImpl
    deactivate InMemRepo
    Repo -> JpaRepo : editChosenCategory()
    activate JpaRepo
    JpaRepo -> JpaRepo : entityManager().find()
    JpaRepo -> Entity : changeCategoryNameTo() / changeDescriptionTo()

    activate Entity

    Entity -> JpaRepo : FigureCategory
    deactivate Entity
    JpaRepo --> Repo : Optional<FigureCategory>
    deactivate JpaRepo
end
    Repo -> CTRL : Optional<FigureCategory>
    deactivate Repo

CTRL --> UI : Optional<FigureCategory>
deactivate CTRL

alt success
    UI -> SD : success message
else failure
    UI -> SD : error message
end

deactivate UI
deactivate SD
@enduml