@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "CRM Collaborator" as Collaborator
participant ":System" as System

activate Collaborator

    activate System

    Collaborator -> System: login()
    System --> Collaborator: authenticated

    deactivate System
    Collaborator -> System: ask to register a show request

    activate System

    System --> Collaborator: request data (customer,duration, figures...)
    deactivate System
    Collaborator -> System: types requested data (customer,duration, figures...)

    activate System

    System --> Collaborator: show all data registered for confirmation
    deactivate System
    Collaborator -> System: registerShowRequest(customer, place, time, numDrones, duration, figures)

    activate System

        System -> System: validations(...)
        activate System

        deactivate System

        System -> System: createShowRequest(customer, numDrones, duration...)
        activate System

        deactivate System

        System -> System: addShowRequestStatus("Created", timestamp)
        activate System

        deactivate System

        System -> System: persistShowRequest()
        activate System

        deactivate System

        System --> Collaborator: show outputs and status of the registration
    deactivate System



deactivate Collaborator




@enduml
